# Generated by Django 3.2.7 on 2021-10-07 12:38

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=datetime.datetime.now),
            preserve_default=False,
        ),
    ]
